### ISSUE TITLE
I wouldn't recommend for slow computers

### ISSUE THREAD

**Issue by VincoDinco** [DeIsaaco/Memory-Game-Screenshot-Tool#1]
If your computer is riddled with malware like mine, it will be very slow, and will not work well, but nothing else works well on this computer either. This thing has also magnified the amount of viruses in my computer, it is like the viruses feed off of this program and reproduce. The creator of this program has autism so it would be great if you guys supported him. Thanks.

Lumince, signing off

**Comment by VincoDinco** [comment]
DO NOT BUY THIS PIECE OF SHIT PROGRAM IT HAS IMMENSE AMOUNTS OF VARIOUS RANSOMWARE PACKED INTO THIS MISLEADING PROGRAM. I THOUGHT SOMETHING AS INNOCENT AS A CHEAT FOR A CHILDREN'S GAME WOULDN'T HAVE SHIT LIKE THIS BUT I WAS WRONG!!!

-Lumince, signing off

**Comment by DeIsaaco** [comment]
I don't have autism lol. If you're reading this and really planning on downloading this then you can just look at the code, it's open source so you can check for yourself if it's a virus or not. Also it sounds like you need a new computer Mr. Vince. 💀
